environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

cache:
  - '%LOCALAPPDATA%\Yarn'

test_script:
  - cmd: yarn run test-win

build: off
